### PR TITLE
New Models for Testing

### PR DESCRIPTION
**Pull request by onthez**
Added objects to test
Clearcoat.lwo - Clearcoat and Clearcoat Gloss with MeshPhysicalMaterial
ColorHighlight.lwo - Color Highlight with MeshPhongMaterial
Luminosity.lwo - Luminosity/emissive intensity/emissive color/emissive texture settings for MeshPhongMaterial and MeshStandardMaterial
UV-Discontinuous-VMAD.lwo - Basic 2 planes with VMAD discontinuous UV map
UV-Discontinuous-VMAD.lwo - Basic Cube with VMAD discontinuous UV map

### CODE REVIEW

**Comment by jds580s** [comment]
Here are some screenshots of what these objects look like in LW for reference.
Clearcoat
image

ColorHighlights
image

Luminosity
image

UV-Discontinuous-VMAD
image

UV-Discontinuous-VMAD-Cube
image

**Comment by sciecode** [comment]
This looks great.

Can you just add a commit including these filenames on the index.html ?

**Comment by onthez** [comment]
Of course, I just pushed that commit.  Thanks!

**Comment by looeee** [comment]
Hey Justin, thanks for these! I've been traveling the last few days so I haven't tested them, but the screenshots look great.

@sciecode if this PR looks good to you, go ahead and merge it 🙂

**Comment by sciecode** [comment]
Thanks

**Pull request merged**
