### PR TITLE
Materials: Physical for BSDF, Clearcoat & Color Highlights.

### PR DESCRIPTION
**Pull request by sciecode**
Implemented Three.js Physical material when model uses BSDF.

Clearcoat
image

Color Highlight
image

### CODE REVIEW

**Comment by onthez** [comment]
Those look great!

**Comment by looeee** [comment]
That looks great! 
I'm not entirely sure what level of difference we can expect by using `MeshPhysicalMaterial` rather than `MeshStandardMaterial`, however there will be some degree of performance reduction, especially on mobile. It's the reason I didn't use `MeshPhysicalMaterial` before. 

To err on the side of caution, since performance is often extremely critical for mobile web applications, I would still default to Standard material and only use Physical material when the ClearCoat parameter is present. @sciecode what do you think?

**Comment by sciecode** [comment]
I went digging a little and most of the reasoning behind separating `MeshStandardMaterial` and `MeshPhysicalMaterial` was just ease of use for regular users, Because physical model includes at least 4 more parameters.

But overtime physical was changed to a Disney-like PBR. Using GGX model for reflection. It's expected to have significant overhead compared to standard material. 

That seems like enough reason to only use this material when ClearCoat is present.

>  I would still default to Standard material and only use Physical material when the ClearCoat parameter is present.

I like that idea. Going to prepare these changes.

**Comment by sciecode** [comment]
This should be ready for merge.

I had to include a check for clearcoat value not being equal to zero, because most BSDF models comes with clearcoat attribute, so just checking its presence wasn't enough.

**Pull request merged**
